### ISSUE TITLE
not multiplayer :(

### ISSUE THREAD

**Issue by alex-paul-htm** [Alriceee/Snake-gaem#1]

**Comment by Alriceee** [comment]
It's a work in progress, I have not had any time on my hands to do more testing. I know that the killcam for when you die is not happening at all.

**Comment by Alriceee** [comment]
if you wanna make multiplayer be my guess, I'm honestly too lazy to use node.js for it.

**Comment by Alriceee** [comment]
no multiplayer, abandoned project.
